image: ubuntu:focal

pipelines:
  default:
    - step:
        script:
          - apt-get update
    - step:
        name: 'Set Locale'
        script:
          - locale
          - apt update 
          - apt install locales
          - locale-gen en_US en_US.UTF-8
          - update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
          - export LANG=en_US.UTF-8
          - locale
    - step:
        name: 'Setup Sources'
        script:
          # - apt install software-properties-common
          # - add-apt-repository universe
          - apt update 
          - apt install curl gnupg lsb-release
          - curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
    - step:
        name: 'Install ROS2'
        script:
          - apt update
          - apt install ros-galactic-desktop
          - source /opt/ros/galactic/setup.bash
#    - parallel: 
#      - step:
#          name: 'Build and Test'
#          script:
#            - echo "Your build and test goes here..."
#      - step:
#          name: 'Lint'
#          script:
#            - echo "Your linting goes here..."
#      - step:
#          name: 'Security scan'
#          script:
#            - echo "Your security scan goes here..."

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
#    - step:
#        name: 'Deployment to Staging'
 #       deployment: staging
  #      script:
 #         - echo "Your deployment to staging script goes here..."
 #   - step:
 #       name: 'Deployment to Production'
 #       deployment: production
 #       trigger: 'manual'
  #      script:
   #       - echo "Your deployment to production script goes here..."
